### ISSUE TITLE
-0.0 different than 0.0

### ISSUE THREAD

**Issue by Darkneew** [Convex-Dev/convex#374] opened 2022-08-02 02:08 UTC
When working with doubles, convex distinguishes 0.0 and -0.0
We can see it here:
![0_and_0](https://user-images.githubusercontent.com/47215589/182276315-0c98f626-b6c1-4891-9b30-762490ddbc42.jpg)

This issue raises other issues in other functions, such as here:
![Capture_decran_2022-08-01_115705](https://user-images.githubusercontent.com/47215589/182276412-2599ec6a-b9fd-4363-9a57-731dd6768f59.jpg)

**Comment by mikera** [comment] 2022-08-22 15:51
This is mostly IEEE754 expected behaviour I think.

Coupled with the fact that `=` in Convex very specifically means "the exact same value" so `0.0` and `-0.0` are different because they are actually distinct IEEE754 double values.

**Comment by mikera** [comment] 2022-10-04 11:28
Closing as behaviour is as intended

**Closed by mikera** 2022-10-04 11:28 UTC
Labels: question
