### ISSUE TITLE
Large blobs (>4KB) fail the round trip assertion property tests.

### ISSUE THREAD

**Issue by jcoultas** [Convex-Dev/convex#357] opened 2022-03-09 02:56 UTC
Issue was observed using branch release-0.7.1. When providing a blob greater than 4KB, the round trip assertion fails. The property test that discovered this issue is available as pull #356. To provide a repeatable result, the attached patch ([convex-issue-test-cases.zip](https://github.com/Convex-Dev/convex/files/8211189/convex-issue-test-cases.zip)) demonstrates a working (testLongBlobWorks) and broken (testLongBlobBroken) test case.

The broken test case throws the following exception:
```
convex.core.exceptions.MissingDataException: Missing 0x3a444668459da89b1ebaa63fabe5c50299dedc15e31e35790fa91972624c2b47 in store EtchStore at: convex-db-5980029732526470943.tmp

    at convex.core.data.RefSoft.getValue(RefSoft.java:78)
    at convex.core.data.BlobTree.getChild(BlobTree.java:188)
    at convex.core.data.BlobTree.equalsBytes(BlobTree.java:242)
    at convex.core.data.Blob.equals(Blob.java:109)
    at convex.core.data.ABlob.equals(ABlob.java:225)
    at convex.core.data.ACell.equals(ACell.java:110)
    at org.junit.Assert.isEquals(Assert.java:133)
    at org.junit.Assert.equalsRegardingNull(Assert.java:129)
    at org.junit.Assert.assertEquals(Assert.java:112)
    at org.junit.Assert.assertEquals(Assert.java:146)
    at convex.comms.GenTestFormat.testLongBlobBroken(GenTestFormat.java:83)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

```

I am a part of a research group at the University of Illinois Chicago that works towards novel methods to detect bugs in software projects. This project is identified as being a good candidate for application of our research method to improve coverage using property tests. The above issue outlines the findings with a pull request of the enhanced property test to document the observed behavior.

**Comment by jcoultas** [comment] 2022-03-20 18:57
See below for an inline example of a working and broken test case.

```
@Test
public void testLongBlobWorks() throws BadFormatException {
   Blob value = Blob.fromHex("f".repeat(8192)); // 4KB
   Ref<ACell> pref = ACell.createPersisted(value); // ensure persisted
   Blob b = Format.encodedBlob(value);
   ACell o = Format.read(b);

   assertEquals(RT.getType(value), RT.getType(o));
   assertEquals(value, o);
   assertEquals(b, Format.encodedBlob(o));
   assertEquals(pref.getValue(), o);
}


@Test
public void testLongBlobBroken() throws BadFormatException {
   Blob value = Blob.fromHex("f".repeat(8194));  // 4KB + 1 byte
   Ref<ACell> pref = ACell.createPersisted(value); // ensure persisted
   Blob b = Format.encodedBlob(value);
   ACell o = Format.read(b);

   assertEquals(RT.getType(value), RT.getType(o));
   assertEquals(value, o);
   assertEquals(b, Format.encodedBlob(o));
   assertEquals(pref.getValue(), o);
}
```

**Comment by mikera** [comment] 2022-03-23 10:11
Thanks! This is very useful. I've been working on a rewrite of the Blob appending code, will try out your test case.

**Comment by mikera** [comment] 2022-03-23 10:11
What was the method you used to find this specific issue? It could be helpful more generally?

**Comment by mikera** [comment] 2022-03-23 11:36
This specific problem is at least partly because a Blob of size 4097 or greater is not "canonical", i.e. it does not have a valid encoding. It needs to be converted to the canonical form before encoding. Will have a think about the best way to do this automatically (i.e. a Java user shouldn't have to care...)

**Comment by jcoultas** [comment] 2022-03-23 17:57
> What was the method you used to find this specific issue? It could be helpful more generally?

It is a technique and tool that we are currently researching and working on a paper describing the method.  When our method is published, I will be more than happy to provide a link to the paper.

**Comment by mikera** [comment] 2022-06-23 18:30
Fixed now in more recent versions, regression test `testLongBlobBroken` added

**Comment by mikera** [comment] 2022-06-23 18:31
FWIW solution was to coerce to canonical type before presisting.

**Closed by mikera** 2022-06-23 18:30 UTC
Labels: bug
